name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Artifacts
        path: D:\a\GoogleDynamicDNS\GoogleDynamicDNS\GoogleDynamicDNS\bin\Release\net6.0\publish\
